name: Go Build and Release

on:
  push:
    branches: [ "main" ]

env:
  GO_VERSION: 1.24.x

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: |
        mkdir -p bin
        for OS in "windows" "darwin" "linux"; do
          for ARCH in "amd64" "arm64"; do
            GOOS=$OS GOARCH=$ARCH CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o bin/${OS}-${ARCH}/main .
          done
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/
        retention-days: 5

    - name: Create or update release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/
        name: Latest Build